import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; //! 모든 페이지 적용
import styles from "./page.module.css"; //! 특정한 페이지나 레이아웃에 적용

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
